function outputFile = build_Yehoshua_System_Gradient_integration_v4_tensor_export()
% Creates a separate tensor-export version from the existing v4 file.
% The original v4 file is not modified.
%
% Build:
%   outputFile = build_Yehoshua_System_Gradient_integration_v4_tensor_export;
%
% Run:
%   [results, tensors] = ...
%       Yehoshua_System_Gradient_integration_v4_temporal_living_tensor_export;

    clc;
    format compact;

    candidates = { ...
        fullfile('/MATLAB Drive/modelTRAINING', ...
            'Yehoshua_System_Gradient_integration_v4_temporal_living.m'), ...
        fullfile(pwd, ...
            'Yehoshua_System_Gradient_integration_v4_temporal_living.m')};

    sourceFile = '';

    for k = 1:numel(candidates)
        if isfile(candidates{k})
            sourceFile = candidates{k};
            break;
        end
    end

    if isempty(sourceFile)
        error(['The v4 source file was not found in ' ...
            '/MATLAB Drive/modelTRAINING or the current folder.']);
    end

    sourceCode = fileread(sourceFile);

    sourceCode = replaceOnceLiteral( ...
        sourceCode, ...
        ['function results = ' ...
         'Yehoshua_System_Gradient_integration_v4_temporal_living()'], ...
        ['function [results, tensors] = ' ...
         'Yehoshua_System_Gradient_integration_' ...
         'v4_temporal_living_tensor_export()']);

    sourceCode = replaceOnceLiteral( ...
        sourceCode, ...
        '''Yehoshua_System_Gradient_integration_v4_temporal_living''', ...
        ['''Yehoshua_System_Gradient_integration_' ...
         'v4_temporal_living_tensor_export''']);

    sourceCode = replaceOnceLiteral( ...
        sourceCode, ...
        'writeRGB16Temporal(finalRGB, outputFile, cfg);', ...
        sprintf([ ...
        'writeRGB16Temporal(finalRGB, outputFile, cfg);\n\n' ...
        '    [tensors, tensorMatFile, tensorH5File] = ...\n' ...
        '        exportTensorFiles( ...\n' ...
        '        I0_RGB, IA_RGB, base, optical, photo, v1, quant, ...\n' ...
        '        gradientState, layers, qGate, network, finalRGB, ...\n' ...
        '        outputFile);']));

    sourceCode = replaceOnceLiteral( ...
        sourceCode, ...
        'results = struct();', ...
        sprintf([ ...
        'results = struct();\n' ...
        '    results.tensor_mat_file = tensorMatFile;\n' ...
        '    results.tensor_h5_file = tensorH5File;']));

    sourceCode = [sourceCode, newline, getTensorExportHelpers()]; 

    outputFile = fullfile( ...
        fileparts(sourceFile), ...
        ['Yehoshua_System_Gradient_integration_' ...
         'v4_temporal_living_tensor_export.m']);

    fileID = fopen(outputFile, 'w');

    if fileID < 0
        error('Could not create tensor-export file: %s', outputFile);
    end

    cleanupObject = onCleanup(@() fclose(fileID)); 
    fwrite(fileID, sourceCode, 'char');

    fprintf('\nCreated without modifying v4:\n%s\n\n', outputFile);
end

%% ========================================================================
function textOut = replaceOnceLiteral(textIn, oldText, newText)

    matchIndex = strfind(textIn, oldText);

    if isempty(matchIndex)
        error('Required v4 text was not found:\n%s', oldText);
    end

    if numel(matchIndex) ~= 1
        error('Expected one match, found %d:\n%s', ...
            numel(matchIndex), oldText);
    end

    indexStart = matchIndex(1);
    indexEnd = indexStart + length(oldText) - 1;

    textOut = [ ...
        textIn(1:indexStart - 1), ...
        newText, ...
        textIn(indexEnd + 1:end)];
end

%% ========================================================================
function helperText = getTensorExportHelpers()

    helperText = sprintf([ ...
'%% ========================================================================\n' ...
'function [tensors, matFile, h5File] = exportTensorFiles( ...\n' ...
'    I0_RGB, IA_RGB, base, optical, photo, v1, quant, ...\n' ...
'    gradientState, layers, qGate, network, finalRGB, ...\n' ...
'    outputImage)\n' ...
'\n' ...
'    tensorOutputDir = fullfile( ...\n' ...
'        fileparts(outputImage), ''tensor_exports'');\n' ...
'\n' ...
'    if ~isfolder(tensorOutputDir)\n' ...
'        mkdir(tensorOutputDir);\n' ...
'    end\n' ...
'\n' ...
'    tensorTag = datestr(now, ''yyyymmdd_HHMMSS_FFF'');\n' ...
'\n' ...
'    baseName = [ ...\n' ...
'        ''Yehoshua_System_Gradient_v4_tensors_'' tensorTag];\n' ...
'\n' ...
'    matFile = fullfile(tensorOutputDir, [baseName ''.mat'']);\n' ...
'    h5File = fullfile(tensorOutputDir, [baseName ''.h5'']);\n' ...
'\n' ...
'    tensors = struct();\n' ...
'\n' ...
'    tensors.input.original_rgb = single(I0_RGB);\n' ...
'    tensors.input.adaptive_rgb = single(IA_RGB);\n' ...
'\n' ...
'    tensors.base.coherence = single(base.coherence);\n' ...
'\n' ...
'    tensors.optical.Q = single(optical.Q);\n' ...
'\n' ...
'    tensors.photo.mean_voltage = single(photo.meanVoltage);\n' ...
'    tensors.photo.voltage = single(photo.voltage);\n' ...
'    tensors.photo.cgmp = single(photo.cgmp);\n' ...
'    tensors.photo.glutamate = single(photo.glutamate);\n' ...
'    tensors.photo.temporal_energy = ...\n' ...
'        single(photo.temporalEnergy);\n' ...
'    tensors.photo.temporal_variance = ...\n' ...
'        single(photo.temporalVariance);\n' ...
'    tensors.photo.temporal_noise = ...\n' ...
'        single(photo.temporalNoise);\n' ...
'    tensors.photo.temporal_phase = ...\n' ...
'        single(photo.temporalPhase);\n' ...
'    tensors.photo.temporal_phase_coherence = ...\n' ...
'        single(photo.temporalPhaseCoherence);\n' ...
'    tensors.photo.temporal_phase_velocity = ...\n' ...
'        single(photo.temporalPhaseVelocity);\n' ...
'    tensors.photo.temporal_trail = ...\n' ...
'        single(photo.temporalTrail);\n' ...
'\n' ...
'    tensors.v1.energy = single(v1.energy);\n' ...
'    tensors.v1.phase = single(v1.phase);\n' ...
'    tensors.v1.phase_coherence = single(v1.phaseCoherence);\n' ...
'    tensors.v1.orientation_coherence = ...\n' ...
'        single(v1.orientationCoherence);\n' ...
'\n' ...
'    tensors.quant.core_glow = single(quant.coreGlow);\n' ...
'\n' ...
'    tensors.gradient.angle = single(gradientState.angle);\n' ...
'    tensors.gradient.energy = single(gradientState.energy);\n' ...
'    tensors.gradient.divergence = ...\n' ...
'        single(gradientState.divergence);\n' ...
'    tensors.gradient.curl = single(gradientState.curl);\n' ...
'    tensors.gradient.layers = single(layers);\n' ...
'\n' ...
'    tensors.qgate.precision = single(qGate.precision);\n' ...
'    tensors.qgate.overload = single(qGate.overload);\n' ...
'    tensors.qgate.integrated_output = ...\n' ...
'        single(qGate.integratedOutput);\n' ...
'    tensors.qgate.local_signal_confidence = ...\n' ...
'        single(qGate.localSignalConfidence);\n' ...
'\n' ...
'    tensors.network.semantic_map = single(network.semanticMap);\n' ...
'    tensors.network.edge_map = single(network.edgeMap);\n' ...
'    tensors.network.activity_map = single(network.activityMap);\n' ...
'    tensors.network.coherent_map = single(network.coherentMap);\n' ...
'\n' ...
'    tensors.output.final_rgb = single(finalRGB);\n' ...
'\n' ...
'    metadata = struct();\n' ...
'    metadata.version = ...\n' ...
'        ''Yehoshua_System_Gradient_integration_v4_temporal_living'';\n' ...
'    metadata.source_file = ...\n' ...
'        [''/MATLAB Drive/modelTRAINING/'' ...\n' ...
'         ''jsonhotel_unified_001_002_SAFE_20260628_181406.h5''];\n' ...
'    metadata.dataset_path = ...\n' ...
'        ''/n_5_composite_field_1000x1000/data'';\n' ...
'    metadata.source_sha256 = ...\n' ...
'        [''5ea6094280c492b0f8051b340a842b2d664da81d40cb19ab97'' ...\n' ...
'         ''c914b7d3306013''];\n' ...
'    metadata.output_image = outputImage;\n' ...
'    metadata.created_local = datestr(now, 31);\n' ...
'\n' ...
'    save(matFile, ''tensors'', ''metadata'', ''-v7.3'');\n' ...
'\n' ...
'    writeTensorH5(h5File, ''/input/original_rgb'', ...\n' ...
'        tensors.input.original_rgb);\n' ...
'    writeTensorH5(h5File, ''/input/adaptive_rgb'', ...\n' ...
'        tensors.input.adaptive_rgb);\n' ...
'    writeTensorH5(h5File, ''/base/coherence'', ...\n' ...
'        tensors.base.coherence);\n' ...
'    writeTensorH5(h5File, ''/optical/Q'', tensors.optical.Q);\n' ...
'\n' ...
'    writeTensorH5(h5File, ''/photo/mean_voltage'', ...\n' ...
'        tensors.photo.mean_voltage);\n' ...
'    writeTensorH5(h5File, ''/photo/voltage'', ...\n' ...
'        tensors.photo.voltage);\n' ...
'    writeTensorH5(h5File, ''/photo/cgmp'', tensors.photo.cgmp);\n' ...
'    writeTensorH5(h5File, ''/photo/glutamate'', ...\n' ...
'        tensors.photo.glutamate);\n' ...
'    writeTensorH5(h5File, ''/photo/temporal_energy'', ...\n' ...
'        tensors.photo.temporal_energy);\n' ...
'    writeTensorH5(h5File, ''/photo/temporal_variance'', ...\n' ...
'        tensors.photo.temporal_variance);\n' ...
'    writeTensorH5(h5File, ''/photo/temporal_noise'', ...\n' ...
'        tensors.photo.temporal_noise);\n' ...
'    writeTensorH5(h5File, ''/photo/temporal_phase'', ...\n' ...
'        tensors.photo.temporal_phase);\n' ...
'    writeTensorH5(h5File, ...\n' ...
'        ''/photo/temporal_phase_coherence'', ...\n' ...
'        tensors.photo.temporal_phase_coherence);\n' ...
'    writeTensorH5(h5File, ...\n' ...
'        ''/photo/temporal_phase_velocity'', ...\n' ...
'        tensors.photo.temporal_phase_velocity);\n' ...
'    writeTensorH5(h5File, ''/photo/temporal_trail'', ...\n' ...
'        tensors.photo.temporal_trail);\n' ...
'\n' ...
'    writeTensorH5(h5File, ''/v1/energy'', tensors.v1.energy);\n' ...
'    writeTensorH5(h5File, ''/v1/phase'', tensors.v1.phase);\n' ...
'    writeTensorH5(h5File, ''/v1/phase_coherence'', ...\n' ...
'        tensors.v1.phase_coherence);\n' ...
'    writeTensorH5(h5File, ''/v1/orientation_coherence'', ...\n' ...
'        tensors.v1.orientation_coherence);\n' ...
'\n' ...
'    writeTensorH5(h5File, ''/quant/core_glow'', ...\n' ...
'        tensors.quant.core_glow);\n' ...
'\n' ...
'    writeTensorH5(h5File, ''/gradient/angle'', ...\n' ...
'        tensors.gradient.angle);\n' ...
'    writeTensorH5(h5File, ''/gradient/energy'', ...\n' ...
'        tensors.gradient.energy);\n' ...
'    writeTensorH5(h5File, ''/gradient/divergence'', ...\n' ...
'        tensors.gradient.divergence);\n' ...
'    writeTensorH5(h5File, ''/gradient/curl'', ...\n' ...
'        tensors.gradient.curl);\n' ...
'    writeTensorH5(h5File, ''/gradient/layers'', ...\n' ...
'        tensors.gradient.layers);\n' ...
'\n' ...
'    writeTensorH5(h5File, ''/qgate/precision'', ...\n' ...
'        tensors.qgate.precision);\n' ...
'    writeTensorH5(h5File, ''/qgate/overload'', ...\n' ...
'        tensors.qgate.overload);\n' ...
'    writeTensorH5(h5File, ''/qgate/integrated_output'', ...\n' ...
'        tensors.qgate.integrated_output);\n' ...
'    writeTensorH5(h5File, ...\n' ...
'        ''/qgate/local_signal_confidence'', ...\n' ...
'        tensors.qgate.local_signal_confidence);\n' ...
'\n' ...
'    writeTensorH5(h5File, ''/network/semantic_map'', ...\n' ...
'        tensors.network.semantic_map);\n' ...
'    writeTensorH5(h5File, ''/network/edge_map'', ...\n' ...
'        tensors.network.edge_map);\n' ...
'    writeTensorH5(h5File, ''/network/activity_map'', ...\n' ...
'        tensors.network.activity_map);\n' ...
'    writeTensorH5(h5File, ''/network/coherent_map'', ...\n' ...
'        tensors.network.coherent_map);\n' ...
'\n' ...
'    writeTensorH5(h5File, ''/output/final_rgb'', ...\n' ...
'        tensors.output.final_rgb);\n' ...
'\n' ...
'    h5writeatt(h5File, ''/'', ''version'', metadata.version);\n' ...
'    h5writeatt(h5File, ''/'', ''source_file'', ...\n' ...
'        metadata.source_file);\n' ...
'    h5writeatt(h5File, ''/'', ''dataset_path'', ...\n' ...
'        metadata.dataset_path);\n' ...
'    h5writeatt(h5File, ''/'', ''source_sha256'', ...\n' ...
'        metadata.source_sha256);\n' ...
'    h5writeatt(h5File, ''/'', ''output_image'', ...\n' ...
'        metadata.output_image);\n' ...
'    h5writeatt(h5File, ''/'', ''created_local'', ...\n' ...
'        metadata.created_local);\n' ...
'\n' ...
'    fprintf(''\\nTensor MAT:\\n%s\\n'', matFile);\n' ...
'    fprintf(''Tensor H5:\\n%s\\n\\n'', h5File);\n' ...
'end\n' ...
'\n' ...
'%% ========================================================================\n' ...
'function writeTensorH5(h5File, datasetPath, data)\n' ...
'\n' ...
'    data = single(data);\n' ...
'    dimensions = size(data);\n' ...
'\n' ...
'    if isscalar(data)\n' ...
'        data = reshape(data, [1, 1]);\n' ...
'        dimensions = [1, 1];\n' ...
'    end\n' ...
'\n' ...
'    chunkSize = dimensions;\n' ...
'\n' ...
'    if numel(chunkSize) >= 1\n' ...
'        chunkSize(1) = min(chunkSize(1), 128);\n' ...
'    end\n' ...
'\n' ...
'    if numel(chunkSize) >= 2\n' ...
'        chunkSize(2) = min(chunkSize(2), 128);\n' ...
'    end\n' ...
'\n' ...
'    for dimensionIndex = 3:numel(chunkSize)\n' ...
'        chunkSize(dimensionIndex) = ...\n' ...
'            min(chunkSize(dimensionIndex), 8);\n' ...
'    end\n' ...
'\n' ...
'    h5create( ...\n' ...
'        h5File, datasetPath, dimensions, ...\n' ...
'        ''Datatype'', ''single'', ...\n' ...
'        ''ChunkSize'', chunkSize, ...\n' ...
'        ''Deflate'', 4);\n' ...
'\n' ...
'    h5write(h5File, datasetPath, data);\n' ...
'end\n']);
end
